name: Build and Deploy to AWS S3

on:
  push:
    paths:
      - 'packages/next1/**'  
    branches:
      - main # Set a branch name to trigger deployment


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'
        
    - name: Deploy to S3
      run: |
        aws s3 sync out s3://ttmik-next-frontend-cdn-s3-dev-bucket
    - name: Invalidation to CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id E3U7DVC38TCYCJ --paths "/*"    
