name: ttmik-next-frontend-prod

on:
  push:
    paths:
      - 'packages/next1/**'  
    branches:
      - main # Set a branch name to trigger deployment


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Change directory to packages/next1 and find out directory
      run: |
        cd packages/next1

    - name: Deploy with pnpm
      run: |
        pnpm run deploy

    # - name: Check next out folder exists and 
    #   run: |
    #     ls out
    #     if [ ! -d "out" ]; then
    #       echo "Directory out does not exist."
    #       exit 1
    #     fi

    - name: Deploy to S3
      run: |
        aws s3 sync out s3://ttmik-next-frontend-cdn-s3-dev-bucket

    - name: Invalidation to CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id E3U7DVC38TCYCJ --paths "/*"    
